repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: mixed-line-ending
        args:
          - --fix=lf
      - id: end-of-file-fixer

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1
    hooks:
      - id: prettier
        types_or:
          - markdown
          - toml
          - yaml

  - repo: https://github.com/omnilib/ufmt
    rev: v1.3.1
    hooks:
      - id: ufmt
        additional_dependencies:
          - black == 21.4b2
          - usort == 0.6.4

  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-docstrings == 1.6.0
        args:
          - --config=.flake8
