channels:
  - defaults
dependencies:
  - flake8
  - codecov
  - pip
  - pip:
    - nltk
    - requests
    - revtok
    - pytest
    - pytest-cov
    - pytest-pythonpath
    - sacremoses
    - spacy
    - sphinx
    - sphinx-rtd-theme
    - tqdm
